name: Documentation Error/Edit Report
description: File a documentation error or suggestion
title: "[documentation]: "
labels: ["documentation"]
assignees:
  - insyri
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this report!"
  - type: textarea
    id: info
    attributes:
      label: "Where is this report relevant to? What should be changed?"
      description: "Also tell us, what do you think it should be changed to?"
      placeholder: "Under which directory; which file?"
      value: "In directory x, in file y, line z; a should be changed to b"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "Additional information"
      description: "What else should we know?"
    validations:
      required: false
