name: CI
on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
jobs: # Future: Linting?
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup and run StyLua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config-path=./.stylua.toml -g **/*.lua -- .
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions [StyLua]"
          if [[ ! -z $(git status -s) ]]; then
            git add .
            git commit -m "CI: StyLua Formatting"
          fi
      - name: Push formatted files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
