name: StyLua
on:
  push:
    branches:
    - master
    - test-actions
  pull_request:
    branches:
    - master
    - test-actions
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: StyLua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --check .
          # Specify `version` to pin a specific version, otherwise action will always use latest version/automatically update
